# Site settings
title: "HTL Leonding 78ABKIF"
description: "Blazor Server Plattform der HTL Leonding - Kurse und Demos"
url: "https://htl-leo.github.io"
baseurl: "/blazor"

# Build settings
markdown: kramdown
permalink: /:categories/:year/:month/:day/:title/

# Collections
collections:
  kurse:
    output: true
    permalink: /kurse/:path/

# Defaults
defaults:
  - scope:
      path: ""
      type: "kurse"
    values:
      layout: "kurs"

# Exclude files
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor
